### ISSUE TITLE
Update `Makefile` to be more robust

### ISSUE THREAD

**Issue by dipinhora** [ponylang/library-project-starter#5]
The current `Makefile` in this repo is a good starting point but the way it defines the relationship between the `test` target and the `build/{PACKAGE}` target is somewhat brittle. Additionally, the lack of example `all` and `deploy` targets (even if commented out) makes for an incomplete example.

The current relationship between the targets caused the build to break for the `pony-stable` project when the `Makefile` was updated. The goal of this issue would be to update the `Makefile` to make it robust to prevent similar breakage for any projects using this template.

**Comment by SeanTAllen** [comment]
This has been done.
